package org.tikito.service.job;

public enum JobType {
    UPDATE_SECURITY_PRICES,
    DELETE_SECURITY_PRICES,

    ENRICH_SECURITY,
    RECALCULATE_HISTORICAL_SECURITY_VALUES,
    RECALCULATE_AGGREGATED_HISTORICAL_SECURITY_VALUES,

    RECALCULATE_HISTORICAL_MONEY_VALUES,
    RECALCULATE_AGGREGATED_HISTORICAL_MONEY_VALUES,
    GROUP_MONEY_TRANSACTIONS
}
