services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: tikito
    restart: always
    networks:
      - tikito_network

  tikito_backend:
    image: tikito/tikito-backend:latest
    container_name: tikito-backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${TIKITO_API_PORT}
      FINNHUB_TOKEN: ${FINNHUB_TOKEN}
    depends_on:
      - mariadb
    restart: always
    networks:
      - tikito_network
    ports:
      - "${TIKITO_API_PORT}:${TIKITO_API_PORT}"

  tikito_ui:
    image: tikito/tikito-ui:latest
    container_name: tikito-ui
    environment:
      TIKITO_API_HOSTNAME: ${TIKITO_API_HOSTNAME}:${TIKITO_API_PORT}
    depends_on:
      - tikito_backend
    restart: always
    networks:
      - tikito_network
    ports:
      - "${TIKITO_UI_PORT}:80"


networks:
  tikito_network:
    driver: bridge