export enum SecurityHoldingGraphDisplayField {
  PRICE = 'PRICE',
  HOLDING_VALUE = 'HOLDING_VALUE',
  DIVIDEND = 'DIVIDEND',
  TAX = 'TAX',
  ADMIN_COST = 'ADMIN_COST',
  WORTH = 'WORTH',
  PERFORMANCE = 'PERFORMANCE',
  CASH_WITHDRAWN = 'CASH_WITHDRAWN',
  CASH_INVESTED = 'CASH_INVESTED',
  MAX_CASH_INVESTED = 'MAX_CASH_INVESTED',
  CASH_ON_HAND = 'CASH_ON_HAND',
  ALL = 'ALL'
}
