export enum JobType {
  UPDATE_SECURITY_PRICES = 'UPDATE_SECURITY_PRICES',
  DELETE_SECURITY_PRICES = 'DELETE_SECURITY_PRICES',
  ENRICH_SECURITY = 'ENRICH_SECURITY',
  RECALCULATE_HISTORICAL_SECURITY_VALUES = 'RECALCULATE_HISTORICAL_SECURITY_VALUES',
  RECALCULATE_AGGREGATED_HISTORICAL_SECURITY_VALUES = 'RECALCULATE_AGGREGATED_HISTORICAL_SECURITY_VALUES',
  RECALCULATE_HISTORICAL_MONEY_VALUES = 'RECALCULATE_HISTORICAL_MONEY_VALUES',
  RECALCULATE_AGGREGATED_HISTORICAL_MONEY_VALUES = 'RECALCULATE_AGGREGATED_HISTORICAL_MONEY_VALUES',
  GROUP_MONEY_TRANSACTIONS = 'GROUP_MONEY_TRANSACTIONS',
  RECALCULATE_LOAN = 'RECALCULATE_LOAN'
}