package org.tikito.dto.security;

public enum SecurityTransactionType {
    BUY,
    BUY_PRODUCT_CHANGE,
    BUY_ISIN_CHANGE,
    SELL,
    SELL_PRODUCT_CHANGE,
    SELL_ISIN_CHANGE,
    DIVIDEND,
    TRANSACTION_COST,
    TAX,
    AANSLUITKOSTEN,
    INTEREST,
    CASH_SWEEP,
    CURRENCY_CREDITING,
    CURRENCY_DEBITING,
    WITHDRAWAL,
    FLATEX_DEPOSIT,
    IDEAL_DEPOSIT,
    THIRD_PARTY_COSTS,
    IDEAL_RESERVATION,
    DIVIDEND_TAX,
    COUNTRY_TAX,
    TRANSFER_FROM,
    TRANSFER_TO,
    ADMIN_COSTS,
    MONEY_DEPOSIT
}
